[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = ADxMrx1unRrSJymoTIGQcKUi7yKrNqZWYLWgxkOqtH4=

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# Windows Client (MATEBOOKD2019)
PublicKey = 2IfgJ8ORHEr40OEgeKuYkLVS9HeC7SFUCvW6HZXrElo=
AllowedIPs = 10.0.0.3/32
